// frontend/monolith-spa-react/src/carts/ProductListItem.js
import React from 'react';

export default function (props) {
  return (
    <li className="list-group-item">
      <div className="media">
        <img
          alt={props.product.name}
          className="mr-3"
          width="64"
          src={`${process.env.REACT_APP_BASE_URL}${props.product.imageUrl[0]}`}
        />
        <div className="media-body">
          <h5 className="mt-0">
            {props.product.name} - {String.fromCharCode(36)}
            {props.product.price}
            <span className="badge badge-pill badge-primary float-right p-list-item-count">
              {props.product.quantity || 1}
            </span>
          </h5>
        </div>
      </div>
    </li>
  );
}

// frontend/client-side-multiple-microfrontends-per-view/microfrontends/carts/src/components/ProductListItemComponent.vue
<template>
  <li class="list-group-item">
    <div class="media">
      <img
        class="mr-3"
        width="64"
        :src="`http://localhost:8080${product.imageUrl[0]}`"
      />
      <div class="media-body">
        <h5 class="mt-0">
          {{product.name}} - &dollar;{{product.price}}
          <span class="badge badge-pill badge-primary float-right p-list-item-count">
            {{ product.quantity || 1 }}
          </span>
        </h5>
      </div>
    </div>
  </li>
</template>

<script>
    export default {
        name: 'ProductListItemComponent',
        props: {
          product: Object
        }
    }
</script>
